### ISSUE TITLE
How to retrieve sampling rate for spike sorting output?

### ISSUE THREAD

**Issue by alejoe91** [flatironinstitute/spikeforest#12]
In this example code (https://github.com/flatironinstitute/spikeforest/blob/main/examples/load_spikeforest_sorting_outputs.py) the sampling frequency for the sorting output is always set to 30000, but that's not the case for all recordings.

How to properly retrieve the correct value?

**Comment by magland** [comment]
The way to do this properly would be to find the corresponding recording from https://github.com/flatironinstitute/spikeforest/blob/main/doc/download-spikeforest-data.md and then lookup the sample rate from there.

**Comment by alejoe91** [comment]
ok, making a PR :)

**Comment by alejoe91** [comment]
https://github.com/flatironinstitute/spikeforest/pull/13
