### ISSUE TITLE
Cannot load recordings

### ISSUE THREAD

**Issue by DradeAW** [flatironinstitute/spikeforest#18]
Hi,

I've installed `kachery` and set up a node with the channel linked to `spikeforest` (with the passcode).
But I did not send my node ID to you as said in the `kachery-dox` "Indicate the roles you would like to perform, and inform the channel owner (through another means of communication) of your name and node id.".
if this is needed, how do I do it?

I tried loading the recordings as described here: https://github.com/flatironinstitute/spikeforest/blob/main/doc/download-spikeforest-data.md

But nothing works:
```python
import sortingview as sv

recording_name = 'paired_kampff/2014_11_25_Pair_3_0'
recording_uri = 'sha1://a205f87cef8b7f86df7a09cddbc79a1fbe5df60f/2014_11_25_Pair_3_0.json'
sorting_uri = 'sha1://c656add63d85a17840980084a1ff1cdc662a2cd5/2014_11_25_Pair_3_0.firings_true.json'

recording = sv.LabboxEphysRecordingExtractor(recording_uri, download=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/nsr/wyngaard/.conda/envs/spikeforest_v2/lib/python3.8/site-packages/sortingview/extractors/labboxephysrecordingextractor.py", line 216, in __init__
    obj = _create_object_for_arg(arg)
  File "/users/nsr/wyngaard/.conda/envs/spikeforest_v2/lib/python3.8/site-packages/sortingview/extractors/labboxephysrecordingextractor.py", line 138, in _create_object_for_arg
    raise Exception(f'Unable to load object: {path}')
Exception: Unable to load object: sha1://a205f87cef8b7f86df7a09cddbc79a1fbe5df60f/2014_11_25_Pair_3_0.json
```

```python
import kachery_client as kc

x = kc.load_json('sha1://f728d5bf1118a8c6e2dfee7c99efb0256246d1d3/studysets.json') # Latest json from https://github.com/flatironinstitute/spikeforest_recordings/blob/master/recordings/studysets
print(x)
>>> None
```

**Comment by magland** [comment]
The passcode should be enough to have permission to request files.
Did you restart your daemon? Does the console output of the daemon show that you are on the spikeforest channel?
From the command-line you can try:
```
kachery-load sha1://f728d5bf1118a8c6e2dfee7c99efb0256246d1d3/studysets.json
```

**Comment by DradeAW** [comment]
Ah it was as simple as to restart the daemon ...

Thank you, and sorry for the dumb issue :)
