### ISSUE TITLE
Unable to download datasets through kachery

### ISSUE THREAD

**Issue by pujaltes** [flatironinstitute/spikeforest#19]
I have been unable to download several datasets through kachery. Last week I was able to connect to the kachery channel and download a very limited number of datasets including:

```
kachery-load sha1://f728d5bf1118a8c6e2dfee7c99efb0256246d1d3/studysets.json
```
However, I am now unable to download any data and only receive None as a response when trying to load data. It seems that the passcode is no longer sufficient to gain access to the channel. I include an image below showing that despite having the passcode I no longer have authorization.

![kachery2](https://user-images.githubusercontent.com/38992512/163204907-87e6bb0d-3c8f-46df-95e5-c11cd760cd5d.png)

Any help would be much appreciated.

**Comment by magland** [comment]
@pujaltes please try the updated instructions. These no longer require running the kachery daemon. Note that only a subset of the recordings are available through this method at this time. And this is all under development, so let me know if it works.

**Comment by pujaltes** [comment]
@magland thank you for the pointing me in the right direction and for updating the instructions, they were very helpful. I was able to download the subset of available recordings.
