### ISSUE TITLE
Update PAIRED_* data to kachery_cloud files

### ISSUE THREAD

**Issue by GandalfTGrey** [flatironinstitute/spikeforest#23]
It's very convenient for users to load data using the code like those in `/example/list_all_recordings.py:`

` hybrid_janelia_uri = 'sha1://00854fd2d82eb1e9cf688b25a943166d62c6d751?spikeforest-recordings.json' `

It will helps a lot if you put other studyset in SpikeForest online using that format(espetially PAIRED studysets).

Appreciate a lot!

**Comment by jsoules** [comment]
I'm glad to hear you find this method convenient!

We have the PAIRED_BOYDEN, PAIRED_CRCNS_HC1, PAIRED_ENGLISH, PAIRED_KAMPFF, and PAIRED_MEA64C_YGER already available by default (it's not obvious from `list_all_recordings.py` but there's a default uri which appears in `spikeforest/load_spikeforest_recordings/load_spikeforest_recordings.py` that refers to these data sets).

I think that just leaves the PAIRED_MONOTRODE study set among the PAIRED_ ones. Are you asking for that to be added specifically? Are there other specific data sets you'd like us to prioritize as well?

**Comment by GandalfTGrey** [comment]
Thanks for replying!
I think the default uri you mentioned is this one:
`default_uri = 'ipfs://bafkreiharnfwm5ntcui4rsex4zkvxfjbytodkserudpvfsnsx5us7tciuq?spikeforest-recordings.json'`

But I think these are only part of the paired data in SpikeForest, using the code below, i got recording num=31, I think there's more on SpikeForest's website

```
import json
import spikeforest as sf
import kachery_cloud as kcl
default_uri = "ipfs://bafkreiharnfwm5ntcui4rsex4zkvxfjbytodkserudpvfsnsx5us7tciuq?spikeforest-recordings.json"
default_json = kcl.load_json(default_uri)
default_rec = default_json['recordings']
print(len(default_rec))
```
![Screenshot from 2022-08-15 10-41-59](https://user-images.githubusercontent.com/49109487/184568576-713d2e53-efaa-42fc-97d7-2accdc10e78d.png)
