### ISSUE TITLE
the new default_uri not working 

### ISSUE THREAD

**Issue by GandalfTGrey** [flatironinstitute/spikeforest#24]
In  `/spikeforest/load_spikeforest_recordings/load_spikeforest_recordings.py` :
`# prepared using: devel/migrate_script1`
`default_uri = 'sha1://1d343ed7e876ffd73bd8e0daf3b8a2c4265b783c?spikeforest-recordings.json'`
this uri not working in this code: `x = kcl.load_json(uri)`

Besides, in `migrate_script1.py`:, `recording_rec_uri = kcl.get_mutable_local(k)` get None for `recording_rec_uri`

**Comment by magland** [comment]
Could you pip upgrade to the latest kachery-cloud, and try to load that
default_uri?

**Comment by magland** [comment]
@GandalfTGrey I am closing this for now, but let me know if it needs to be reopened.
