### ISSUE TITLE
Request for MultiUnit Datasets and How to get the particular recording data

### ISSUE THREAD

**Issue by gjj0430** [flatironinstitute/spikeforest#26]
Hello! I am working with multiunit spike sorting, could you please update the datasets like **HYBRID_JANELIA**? Prior works on it used the **Kachery** package, which is not available now, so it confuses me a lot.
By the way, I don't know how to get the particluar data using the script provided. I used the _load_extractors_for_recording.py_ ,but I can only get the overall information about the recording, please give me some instructions on this powerful tool.

 I would appreciate it if you can reply soon!

**Comment by magland** [comment]
Hi @gjj0430 I have just updated the URI for hybrid janelia. See the comments in this script:

https://github.com/flatironinstitute/spikeforest/blob/main/examples/list_all_recordings.py

Be sure that you have the latest version of kachery-cloud installed and set up properly.

You can use examples/load_extractors_for_recording.py to load the spikeinterface objects. See the spikeinterface project for more info on working with those objects.

**Comment by gjj0430** [comment]
Thank you, sir! I couldn't be more grateful to your timely reply!
